# Generated by Django 5.1.2 on 2024-11-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankloan',
            fields=[
                ('Bank_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Bank_name', models.CharField(max_length=100)),
                ('Customer_name', models.CharField(max_length=100)),
                ('Loan_amount', models.IntegerField()),
                ('Customer_mobile_number', models.IntegerField()),
                ('Loan_Date', models.DateField()),
            ],
        ),
    ]
